server:
  port: 9001
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gigoya_user
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

## Actuator ##
management:
  endpoints:
    web:
      exposure:
        include: health,info

## OpenApi Settings ##
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: "/docs/swagger-ui.html"

openapi:
  app:
    title: "VolSys Utility API"
    description: "This project aims to provide utility operations for all VolSys services."
    version: 1.0
    contact : "Contact Support"
    email: "info@talls.tech"
    licence: "Tallstech 1.0"
    url: "https://www.talls.tech"
